language: php

dist: precise

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests/
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
